"""empty message

Revision ID: 920c5f55850a
Revises: 76259d6d1a83
Create Date: 2021-04-18 00:30:55.234933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '920c5f55850a'
down_revision = '76259d6d1a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('birth_year', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('birth_year', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skin_color', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('hair_color', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('people')
    # ### end Alembic commands ###
